# Generated by Django 5.1.4 on 2024-12-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('s3_key', models.CharField(max_length=255, unique=True)),
                ('s3_url', models.URLField()),
            ],
        ),
    ]
